using D365SqlStagingGenerator.Config;
using D365SqlStagingGenerator.Services;
using Microsoft.Extensions.Configuration;

namespace D365SqlStagingGenerator;

public static class Program
{
    public static int Main(string[] args)
    {
        try
        {
            var configPath = args.Length > 0 ? args[0] : "appsettings.json";

            var builder = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile(configPath, optional: false, reloadOnChange: false)
                .AddJsonFile("appsettings.local.json", optional: true, reloadOnChange: false)
                .AddEnvironmentVariables("D365SSG_");

            var configuration = builder.Build();
            var appConfig = configuration.Get<AppConfig>() ?? new AppConfig();

            if (appConfig.Entities.Count == 0)
            {
                Console.Error.WriteLine("No entities configured. Add entity logical names to the 'Entities' array in appsettings.json.");
                return 1;
            }

            Directory.CreateDirectory(appConfig.Output.Directory);

            Console.WriteLine($"Connecting to Dataverse at {appConfig.Dataverse.Url} ...");
            using var metadataService = new DataverseMetadataService(appConfig.Dataverse);
            var generator = new SqlScriptGenerator(appConfig.Output);

            var combined = new System.Text.StringBuilder();
            combined.AppendLine("-- Generated by D365SqlStagingGenerator");
            combined.AppendLine($"-- Generated at: {DateTime.UtcNow:O}");
            combined.AppendLine($"-- Source: {appConfig.Dataverse.Url}");
            combined.AppendLine();

            var failures = new List<(string Entity, string Error)>();

            foreach (var entityName in appConfig.Entities)
            {
                try
                {
                    Console.WriteLine($"  - Retrieving metadata for '{entityName}' ...");
                    var entity = metadataService.RetrieveEntity(entityName);
                    var script = generator.Generate(entity);

                    if (appConfig.Output.GenerateSingleFile)
                    {
                        combined.AppendLine(script);
                    }
                    else
                    {
                        var file = Path.Combine(
                            appConfig.Output.Directory,
                            $"{appConfig.Output.TablePrefix}{entity.LogicalName}.sql");
                        File.WriteAllText(file, script);
                        Console.WriteLine($"    -> {file}");
                    }
                }
                catch (Exception ex)
                {
                    Console.Error.WriteLine($"    ! Failed for '{entityName}': {ex.Message}");
                    failures.Add((entityName, ex.Message));
                }
            }

            if (appConfig.Output.GenerateSingleFile)
            {
                var singleFile = Path.Combine(appConfig.Output.Directory, appConfig.Output.SingleFileName);
                File.WriteAllText(singleFile, combined.ToString());
                Console.WriteLine($"Wrote combined script -> {singleFile}");
            }

            if (failures.Count > 0)
            {
                Console.Error.WriteLine();
                Console.Error.WriteLine($"Completed with {failures.Count} failure(s):");
                foreach (var (entity, error) in failures)
                    Console.Error.WriteLine($"  - {entity}: {error}");
                return 2;
            }

            Console.WriteLine("Done.");
            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Fatal error: {ex.Message}");
            Console.Error.WriteLine(ex.ToString());
            return 1;
        }
    }
}
